version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hs_postgres
    restart: always
    environment:
      POSTGRES_DB: HS_DB
      POSTGRES_USER: hs_user
      POSTGRES_PASSWORD: hs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: